#!/usr/bin/env python3
"""
Pretendard self-hosted dynamic subset 빌드 (2026-09 리디자인 Phase A).

- 입력: npm `pretendard` 패키지의 variable dynamic-subset(92 청크, unicode-range 분할)
- 처리: 각 청크의 wght 축을 400–800 으로 제한(fontTools instancer) → 청크당 ~30% 감소
        (사이트에서 쓰는 굵기는 400/500/600/700/800 뿐)
- 출력: public/fonts/pretendard/pv-<idx>.<hash>.woff2  (콘텐츠 해시 → immutable 캐시)
        app/fonts.css  (@font-face × 92, unicode-range — 브라우저는 페이지에 실제 쓰인 글자 청크만 다운로드)

사용법:
  cd /tmp && npm pack pretendard && tar xzf pretendard-*.tgz   # → /tmp/package
  python3 scripts/build-font-subsets.py /tmp/package
필요: pip install fonttools brotli
"""
import hashlib
import io
import os
import re
import sys

from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

WGHT_MIN, WGHT_MAX = 400, 800

def main():
    pkg = sys.argv[1] if len(sys.argv) > 1 else "/tmp/package"
    base = os.path.join(pkg, "dist/web/variable")
    css = open(os.path.join(base, "pretendardvariable-dynamic-subset.css"), encoding="utf-8").read()
    blocks = re.findall(
        r"src: url\(\./woff2-dynamic-subset/(PretendardVariable\.subset\.(\d+)\.woff2)\).*?unicode-range: ([^;]+);",
        css,
        re.S,
    )
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_dir = os.path.join(root, "public/fonts/pretendard")
    os.makedirs(out_dir, exist_ok=True)
    for f in os.listdir(out_dir):
        if f.endswith(".woff2"):
            os.remove(os.path.join(out_dir, f))

    faces = []
    total = 0
    for fname, idx, urange in blocks:
        font = TTFont(os.path.join(base, "woff2-dynamic-subset", fname))
        font = instancer.instantiateVariableFont(font, {"wght": (WGHT_MIN, WGHT_MAX)})
        font.flavor = "woff2"
        buf = io.BytesIO()
        font.save(buf)
        data = buf.getvalue()
        h = hashlib.sha1(data).hexdigest()[:8]
        out_name = f"pv-{idx}.{h}.woff2"
        with open(os.path.join(out_dir, out_name), "wb") as fh:
            fh.write(data)
        total += len(data)
        faces.append(
            "@font-face{font-family:\"Pretendard\";font-style:normal;font-display:swap;"
            f"font-weight:{WGHT_MIN} {WGHT_MAX};"
            f"src:url(/fonts/pretendard/{out_name}) format(\"woff2-variations\"),url(/fonts/pretendard/{out_name}) format(\"woff2\");"
            f"unicode-range:{urange.strip()}}}"
        )

    header = (
        "/* AUTO-GENERATED by scripts/build-font-subsets.py — 직접 수정 금지.\n"
        "   Pretendard Variable (OFL-1.1, github.com/orioncactus/pretendard) dynamic subset,\n"
        f"   wght {WGHT_MIN}-{WGHT_MAX} 로 축 제한. 청크 {len(faces)}개, 총 {total // 1024}KB (페이지는 쓰인 청크만 받음). */\n"
    )
    with open(os.path.join(root, "app/fonts.css"), "w", encoding="utf-8") as fh:
        fh.write(header + "\n".join(faces) + "\n")
    print(f"chunks={len(faces)} total={total // 1024}KB")

if __name__ == "__main__":
    main()
